version: '3'

services:
  db:
    image: mysql:5.7
    container_name: coisas_db
    environment:
      MYSQL_ROOT_PASSWORD: coisas
      MYSQL_DATABASE: coisas
      MYSQL_USER: coisas
      MYSQL_PASSWORD: coisas
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    image: equinalha/coisas_web:latest
    container_name: coisas_web
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
